[package]
name = "scale-borrow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-scale-codec = { version = "3.1.5", default-features = false, features = [] }
scale-info = { version= "*", default-features = false, features = []  }
frame-metadata = { version="15.0", default-features = false, features = ["v14"] }

[dev-dependencies]
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["full"] }